global:
  scrape_interval: 2s
  evaluation_interval: 2s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'data-ingestion'
    static_configs:
      - targets: ['data-ingestion:8000']

  - job_name: 'data-storage'
    static_configs:
      - targets: ['data-storage:8001']

  - job_name: 'analytics-service'
    static_configs:
      - targets: ['analytics-service:8002']

  - job_name: 'resource-monitor'
    static_configs:
      - targets: ['resource-monitor:8083']
